# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designAfterWindowed.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1362, 725)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.Form = QtGui.QWidget(MainWindow)
        self.Form.setObjectName(_fromUtf8("Form"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxGenome = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxGenome.setObjectName(_fromUtf8("comboBoxGenome"))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxGenome, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBoxProject = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxProject.setObjectName(_fromUtf8("comboBoxProject"))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxProject, 0, 4, 1, 1)
        self.lineEditGeneralSearch = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditGeneralSearch.setObjectName(_fromUtf8("lineEditGeneralSearch"))
        self.gridLayout.addWidget(self.lineEditGeneralSearch, 1, 0, 1, 5)
        self.pushButtonClear = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.gridLayout.addWidget(self.pushButtonClear, 1, 5, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout.addWidget(self.lineEditName, 2, 0, 1, 2)
        self.lineEditBiosource = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBiosource.setObjectName(_fromUtf8("lineEditBiosource"))
        self.gridLayout.addWidget(self.lineEditBiosource, 2, 2, 1, 2)
        self.lineEditDataType = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditDataType.setObjectName(_fromUtf8("lineEditDataType"))
        self.gridLayout.addWidget(self.lineEditDataType, 2, 4, 1, 1)
        self.lineEditDescription = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditDescription.setObjectName(_fromUtf8("lineEditDescription"))
        self.gridLayout.addWidget(self.lineEditDescription, 3, 0, 1, 2)
        self.lineEditTechnique = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditTechnique.setObjectName(_fromUtf8("lineEditTechnique"))
        self.gridLayout.addWidget(self.lineEditTechnique, 3, 2, 1, 2)
        self.lineEditEpigenetic = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditEpigenetic.setObjectName(_fromUtf8("lineEditEpigenetic"))
        self.gridLayout.addWidget(self.lineEditEpigenetic, 3, 4, 1, 1)
        self.label.raise_()
        self.lineEditBiosource.raise_()
        self.label_2.raise_()
        self.comboBoxGenome.raise_()
        self.pushButtonClear.raise_()
        self.lineEditDataType.raise_()
        self.lineEditGeneralSearch.raise_()
        self.lineEditName.raise_()
        self.comboBoxProject.raise_()
        self.lineEditDescription.raise_()
        self.lineEditTechnique.raise_()
        self.lineEditEpigenetic.raise_()
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.dataTable = QtGui.QTableView(self.groupBox)
        self.dataTable.setGeometry(QtCore.QRect(0, 23, 801, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.dataTable.setSortingEnabled(True)
        self.dataTable.setObjectName(_fromUtf8("dataTable"))
        self.dataTable.verticalHeader().setVisible(True)
        self.dataTable.verticalHeader().setHighlightSections(False)
        self.dataTableSelected = QtGui.QTableView(self.groupBox)
        self.dataTableSelected.setGeometry(QtCore.QRect(0, 260, 801, 111))
        self.dataTableSelected.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTableSelected.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.dataTableSelected.setSortingEnabled(True)
        self.dataTableSelected.setObjectName(_fromUtf8("dataTableSelected"))
        self.dataTableSelected.verticalHeader().setVisible(True)
        self.dataTableSelected.verticalHeader().setHighlightSections(False)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 370, 801, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButtonExport = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonExport.setGeometry(QtCore.QRect(702, 10, 86, 41))
        self.pushButtonExport.setObjectName(_fromUtf8("pushButtonExport"))
        self.pushButtonRemove = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonRemove.setGeometry(QtCore.QRect(410, 10, 86, 41))
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.pushButtonAdd = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonAdd.setGeometry(QtCore.QRect(300, 10, 86, 41))
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 91, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dataTable.raise_()
        self.dataTable.raise_()
        self.dataTableSelected.raise_()
        self.groupBox_2.raise_()
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(768, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 3)
        self.groupBox_4 = QtGui.QGroupBox(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(498, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tableViewMeta = QtGui.QTableView(self.groupBox_4)
        self.tableViewMeta.setGeometry(QtCore.QRect(0, 23, 481, 349))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewMeta.sizePolicy().hasHeightForWidth())
        self.tableViewMeta.setSizePolicy(sizePolicy)
        self.tableViewMeta.setAutoScroll(True)
        self.tableViewMeta.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableViewMeta.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableViewMeta.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableViewMeta.setShowGrid(False)
        self.tableViewMeta.setSortingEnabled(False)
        self.tableViewMeta.setObjectName(_fromUtf8("tableViewMeta"))
        self.tableViewMeta.horizontalHeader().setStretchLastSection(True)
        self.tableViewMeta.verticalHeader().setVisible(False)
        self.tableViewMeta.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.Form)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1362, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Genome:", None))
        self.comboBoxGenome.setItemText(0, _translate("MainWindow", "Neues Element", None))
        self.comboBoxGenome.setItemText(1, _translate("MainWindow", "bbbbbb", None))
        self.comboBoxGenome.setItemText(2, _translate("MainWindow", "jjutr", None))
        self.comboBoxGenome.setItemText(3, _translate("MainWindow", "sagege", None))
        self.label_2.setText(_translate("MainWindow", "Project:", None))
        self.comboBoxProject.setItemText(0, _translate("MainWindow", "Neues Element", None))
        self.comboBoxProject.setItemText(1, _translate("MainWindow", "bbbbbb", None))
        self.comboBoxProject.setItemText(2, _translate("MainWindow", "jjutr", None))
        self.comboBoxProject.setItemText(3, _translate("MainWindow", "sagege", None))
        self.lineEditGeneralSearch.setPlaceholderText(_translate("MainWindow", "General Search", None))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear All", None))
        self.lineEditName.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.lineEditBiosource.setPlaceholderText(_translate("MainWindow", "Biosource", None))
        self.lineEditDataType.setPlaceholderText(_translate("MainWindow", "Data Type", None))
        self.lineEditDescription.setPlaceholderText(_translate("MainWindow", "Description", None))
        self.lineEditTechnique.setPlaceholderText(_translate("MainWindow", "Technique", None))
        self.lineEditEpigenetic.setPlaceholderText(_translate("MainWindow", "Epigen. Mark", None))
        self.groupBox.setTitle(_translate("MainWindow", "Experiments", None))
        self.pushButtonExport.setText(_translate("MainWindow", "Export", None))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove", None))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add", None))
        self.label_3.setText(_translate("MainWindow", "Exp. Matrix", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Metadata", None))

