# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(847, 725)
        self.Form = QtGui.QWidget(MainWindow)
        self.Form.setObjectName(_fromUtf8("Form"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Form)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditEpigenetic = QtGui.QLineEdit(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEpigenetic.sizePolicy().hasHeightForWidth())
        self.lineEditEpigenetic.setSizePolicy(sizePolicy)
        self.lineEditEpigenetic.setObjectName(_fromUtf8("lineEditEpigenetic"))
        self.gridLayout_5.addWidget(self.lineEditEpigenetic, 3, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.Form)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.Form)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout_5.addWidget(self.lineEditName, 2, 1, 1, 1)
        self.lineEditDescription = QtGui.QLineEdit(self.Form)
        self.lineEditDescription.setObjectName(_fromUtf8("lineEditDescription"))
        self.gridLayout_5.addWidget(self.lineEditDescription, 3, 1, 1, 1)
        self.lineEditTechnique = QtGui.QLineEdit(self.Form)
        self.lineEditTechnique.setObjectName(_fromUtf8("lineEditTechnique"))
        self.gridLayout_5.addWidget(self.lineEditTechnique, 3, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.Form)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 3, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 2, 2, 1, 1)
        self.lineEditBiosource = QtGui.QLineEdit(self.Form)
        self.lineEditBiosource.setObjectName(_fromUtf8("lineEditBiosource"))
        self.gridLayout_5.addWidget(self.lineEditBiosource, 2, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.Form)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.Form)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.Form)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.Form)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 3, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 3, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.Form)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.comboBoxGenome = QtGui.QComboBox(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxGenome.sizePolicy().hasHeightForWidth())
        self.comboBoxGenome.setSizePolicy(sizePolicy)
        self.comboBoxGenome.setObjectName(_fromUtf8("comboBoxGenome"))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.comboBoxGenome.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBoxGenome, 0, 1, 1, 1)
        self.lineEditDataType = QtGui.QLineEdit(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDataType.sizePolicy().hasHeightForWidth())
        self.lineEditDataType.setSizePolicy(sizePolicy)
        self.lineEditDataType.setObjectName(_fromUtf8("lineEditDataType"))
        self.gridLayout_5.addWidget(self.lineEditDataType, 2, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBoxProject = QtGui.QComboBox(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxProject.sizePolicy().hasHeightForWidth())
        self.comboBoxProject.setSizePolicy(sizePolicy)
        self.comboBoxProject.setObjectName(_fromUtf8("comboBoxProject"))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.comboBoxProject.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBoxProject, 0, 4, 1, 1)
        self.lineEditGeneralSearch = QtGui.QLineEdit(self.Form)
        self.lineEditGeneralSearch.setObjectName(_fromUtf8("lineEditGeneralSearch"))
        self.gridLayout_5.addWidget(self.lineEditGeneralSearch, 1, 1, 1, 7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButtonClear = QtGui.QPushButton(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClear.sizePolicy().hasHeightForWidth())
        self.pushButtonClear.setSizePolicy(sizePolicy)
        self.pushButtonClear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonClear.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.horizontalLayout_2.addWidget(self.pushButtonClear)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 3, 0, 1, 7)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableViewMeta = QtGui.QTableView(self.Form)
        self.tableViewMeta.setAutoScroll(True)
        self.tableViewMeta.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableViewMeta.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableViewMeta.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableViewMeta.setShowGrid(False)
        self.tableViewMeta.setSortingEnabled(False)
        self.tableViewMeta.setObjectName(_fromUtf8("tableViewMeta"))
        self.tableViewMeta.horizontalHeader().setStretchLastSection(True)
        self.tableViewMeta.verticalHeader().setVisible(False)
        self.tableViewMeta.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.tableViewMeta, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.dataTable = QtGui.QTableView(self.Form)
        self.dataTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.dataTable.setSortingEnabled(True)
        self.dataTable.setObjectName(_fromUtf8("dataTable"))
        self.dataTable.verticalHeader().setVisible(True)
        self.dataTable.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.dataTable, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.label_5 = QtGui.QLabel(self.Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.dataTableSelected = QtGui.QTableView(self.Form)
        self.dataTableSelected.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTableSelected.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.dataTableSelected.setSortingEnabled(True)
        self.dataTableSelected.setObjectName(_fromUtf8("dataTableSelected"))
        self.dataTableSelected.verticalHeader().setVisible(True)
        self.dataTableSelected.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.dataTableSelected)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonAdd = QtGui.QPushButton(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtGui.QPushButton(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonRemove.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRemove.setIcon(icon1)
        self.pushButtonRemove.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonRemove.setCheckable(False)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.horizontalLayout.addWidget(self.pushButtonRemove)
        spacerItem7 = QtGui.QSpacerItem(330, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.pushButtonExport = QtGui.QPushButton(self.Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExport.sizePolicy().hasHeightForWidth())
        self.pushButtonExport.setSizePolicy(sizePolicy)
        self.pushButtonExport.setMinimumSize(QtCore.QSize(150, 35))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExport.setIcon(icon2)
        self.pushButtonExport.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonExport.setObjectName(_fromUtf8("pushButtonExport"))
        self.horizontalLayout.addWidget(self.pushButtonExport)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(2, 15)
        self.verticalLayout.setStretch(5, 5)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.Form)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGeneralSearch.clear)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditName.clear)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditDescription.clear)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditBiosource.clear)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditTechnique.clear)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditDataType.clear)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditEpigenetic.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RGT Experiment Browser", None))
        self.label_6.setText(_translate("MainWindow", "Filter and Search", None))
        self.label.setText(_translate("MainWindow", "Genome:", None))
        self.lineEditEpigenetic.setPlaceholderText(_translate("MainWindow", "Epigen. Marker", None))
        self.label_8.setText(_translate("MainWindow", "Description:", None))
        self.lineEditName.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.lineEditDescription.setPlaceholderText(_translate("MainWindow", "Description", None))
        self.lineEditTechnique.setPlaceholderText(_translate("MainWindow", "Technique", None))
        self.label_10.setText(_translate("MainWindow", "Technique:", None))
        self.lineEditBiosource.setPlaceholderText(_translate("MainWindow", "Biosource", None))
        self.label_9.setText(_translate("MainWindow", "Biosource: ", None))
        self.label_7.setText(_translate("MainWindow", "Name:", None))
        self.label_11.setText(_translate("MainWindow", "Type:", None))
        self.label_12.setText(_translate("MainWindow", "Marker:", None))
        self.label_13.setText(_translate("MainWindow", "Search:", None))
        self.comboBoxGenome.setItemText(0, _translate("MainWindow", "Neues Element", None))
        self.comboBoxGenome.setItemText(1, _translate("MainWindow", "bbbbbb", None))
        self.comboBoxGenome.setItemText(2, _translate("MainWindow", "jjutr", None))
        self.comboBoxGenome.setItemText(3, _translate("MainWindow", "sagege", None))
        self.lineEditDataType.setPlaceholderText(_translate("MainWindow", "Data Type", None))
        self.label_2.setText(_translate("MainWindow", "Project:", None))
        self.comboBoxProject.setItemText(0, _translate("MainWindow", "Neues Element", None))
        self.comboBoxProject.setItemText(1, _translate("MainWindow", "bbbbbb", None))
        self.comboBoxProject.setItemText(2, _translate("MainWindow", "jjutr", None))
        self.comboBoxProject.setItemText(3, _translate("MainWindow", "sagege", None))
        self.lineEditGeneralSearch.setPlaceholderText(_translate("MainWindow", "General Search", None))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear All", None))
        self.label_3.setText(_translate("MainWindow", "Experiments", None))
        self.label_4.setText(_translate("MainWindow", "Metadata", None))
        self.label_5.setText(_translate("MainWindow", "Selected Experiments", None))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add", None))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove", None))
        self.pushButtonExport.setText(_translate("MainWindow", " RGT...", None))

import icons_rc
