# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_emExportDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(988, 699)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.emExport = QtGui.QTableWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.emExport.sizePolicy().hasHeightForWidth())
        self.emExport.setSizePolicy(sizePolicy)
        self.emExport.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.emExport.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.emExport.setObjectName(_fromUtf8("emExport"))
        self.emExport.setColumnCount(0)
        self.emExport.setRowCount(0)
        self.verticalLayout.addWidget(self.emExport)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Export = QtGui.QWidget()
        self.Export.setObjectName(_fromUtf8("Export"))
        self.exportButton = QtGui.QPushButton(self.Export)
        self.exportButton.setGeometry(QtCore.QRect(20, 50, 85, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.tabWidget.addTab(self.Export, _fromUtf8(""))
        self.Lineplot = QtGui.QWidget()
        self.Lineplot.setObjectName(_fromUtf8("Lineplot"))
        self.layoutWidget = QtGui.QWidget(self.Lineplot)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 441, 252))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.WhereLineplot = QtGui.QLineEdit(self.layoutWidget)
        self.WhereLineplot.setObjectName(_fromUtf8("WhereLineplot"))
        self.horizontalLayout_3.addWidget(self.WhereLineplot)
        self.WhereBrowserLineplot = QtGui.QToolButton(self.layoutWidget)
        self.WhereBrowserLineplot.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.WhereBrowserLineplot.setArrowType(QtCore.Qt.NoArrow)
        self.WhereBrowserLineplot.setObjectName(_fromUtf8("WhereBrowserLineplot"))
        self.horizontalLayout_3.addWidget(self.WhereBrowserLineplot)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.normalization = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalization.sizePolicy().hasHeightForWidth())
        self.normalization.setSizePolicy(sizePolicy)
        self.normalization.setObjectName(_fromUtf8("normalization"))
        self.normalization.addItem(_fromUtf8(""))
        self.normalization.addItem(_fromUtf8(""))
        self.normalization.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.normalization)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.column = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column.sizePolicy().hasHeightForWidth())
        self.column.setSizePolicy(sizePolicy)
        self.column.setObjectName(_fromUtf8("column"))
        self.column.addItem(_fromUtf8(""))
        self.column.addItem(_fromUtf8(""))
        self.column.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.column)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.row = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row.sizePolicy().hasHeightForWidth())
        self.row.setSizePolicy(sizePolicy)
        self.row.setObjectName(_fromUtf8("row"))
        self.row.addItem(_fromUtf8(""))
        self.row.addItem(_fromUtf8(""))
        self.row.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.row)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.color = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color.sizePolicy().hasHeightForWidth())
        self.color.setSizePolicy(sizePolicy)
        self.color.setObjectName(_fromUtf8("color"))
        self.color.addItem(_fromUtf8(""))
        self.color.addItem(_fromUtf8(""))
        self.color.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.color)
        self.runLineplot = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runLineplot.sizePolicy().hasHeightForWidth())
        self.runLineplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.runLineplot.setFont(font)
        self.runLineplot.setObjectName(_fromUtf8("runLineplot"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.runLineplot)
        self.tabWidget.addTab(self.Lineplot, _fromUtf8(""))
        self.Tests = QtGui.QWidget()
        self.Tests.setObjectName(_fromUtf8("Tests"))
        self.layoutWidget_2 = QtGui.QWidget(self.Tests)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 441, 290))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.WhereTests = QtGui.QLineEdit(self.layoutWidget_2)
        self.WhereTests.setObjectName(_fromUtf8("WhereTests"))
        self.horizontalLayout_6.addWidget(self.WhereTests)
        self.WhereBrowserTests = QtGui.QToolButton(self.layoutWidget_2)
        self.WhereBrowserTests.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.WhereBrowserTests.setArrowType(QtCore.Qt.NoArrow)
        self.WhereBrowserTests.setObjectName(_fromUtf8("WhereBrowserTests"))
        self.horizontalLayout_6.addWidget(self.WhereBrowserTests)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_15 = QtGui.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.input = QtGui.QLineEdit(self.layoutWidget_2)
        self.input.setObjectName(_fromUtf8("input"))
        self.horizontalLayout_7.addWidget(self.input)
        self.inputBrowser = QtGui.QToolButton(self.layoutWidget_2)
        self.inputBrowser.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.inputBrowser.setArrowType(QtCore.Qt.NoArrow)
        self.inputBrowser.setObjectName(_fromUtf8("inputBrowser"))
        self.horizontalLayout_7.addWidget(self.inputBrowser)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_16 = QtGui.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.inputType = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputType.sizePolicy().hasHeightForWidth())
        self.inputType.setSizePolicy(sizePolicy)
        self.inputType.setObjectName(_fromUtf8("inputType"))
        self.inputType.addItem(_fromUtf8(""))
        self.inputType.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.inputType)
        self.label_11 = QtGui.QLabel(self.layoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.testType = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testType.sizePolicy().hasHeightForWidth())
        self.testType.setSizePolicy(sizePolicy)
        self.testType.setObjectName(_fromUtf8("testType"))
        self.testType.addItem(_fromUtf8(""))
        self.testType.addItem(_fromUtf8(""))
        self.testType.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.testType)
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.groupBy = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBy.sizePolicy().hasHeightForWidth())
        self.groupBy.setSizePolicy(sizePolicy)
        self.groupBy.setObjectName(_fromUtf8("groupBy"))
        self.groupBy.addItem(_fromUtf8(""))
        self.groupBy.addItem(_fromUtf8(""))
        self.groupBy.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.groupBy)
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_13)
        self.randomization = QtGui.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomization.sizePolicy().hasHeightForWidth())
        self.randomization.setSizePolicy(sizePolicy)
        self.randomization.setMaximum(999999)
        self.randomization.setProperty("value", 500)
        self.randomization.setObjectName(_fromUtf8("randomization"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.randomization)
        self.runTests = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runTests.sizePolicy().hasHeightForWidth())
        self.runTests.setSizePolicy(sizePolicy)
        self.runTests.setObjectName(_fromUtf8("runTests"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.runTests)
        self.tabWidget.addTab(self.Tests, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Experimental Matrix Export", None))
        self.exportButton.setText(_translate("Dialog", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Export), _translate("Dialog", "Export", None))
        self.label_4.setText(_translate("Dialog", "Save as:", None))
        self.WhereBrowserLineplot.setText(_translate("Dialog", "...", None))
        self.label_5.setText(_translate("Dialog", "Normalization:", None))
        self.normalization.setItemText(0, _translate("Dialog", "None", None))
        self.normalization.setItemText(1, _translate("Dialog", "Rows", None))
        self.normalization.setItemText(2, _translate("Dialog", "Columns", None))
        self.label_6.setText(_translate("Dialog", "Column:", None))
        self.column.setItemText(0, _translate("Dialog", "None", None))
        self.column.setItemText(1, _translate("Dialog", "Reads", None))
        self.column.setItemText(2, _translate("Dialog", "Regions", None))
        self.label_7.setText(_translate("Dialog", "Row:", None))
        self.row.setItemText(0, _translate("Dialog", "None", None))
        self.row.setItemText(1, _translate("Dialog", "Reads", None))
        self.row.setItemText(2, _translate("Dialog", "Regions", None))
        self.label_8.setText(_translate("Dialog", "Color:", None))
        self.color.setItemText(0, _translate("Dialog", "None", None))
        self.color.setItemText(1, _translate("Dialog", "Reads", None))
        self.color.setItemText(2, _translate("Dialog", "Regions", None))
        self.runLineplot.setText(_translate("Dialog", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Lineplot), _translate("Dialog", "Lineplot", None))
        self.label_10.setText(_translate("Dialog", "Save as:", None))
        self.WhereBrowserTests.setText(_translate("Dialog", "...", None))
        self.label_15.setText(_translate("Dialog", "Input Matrix:", None))
        self.inputBrowser.setText(_translate("Dialog", "...", None))
        self.label_16.setText(_translate("Dialog", "Input Type:", None))
        self.inputType.setItemText(0, _translate("Dialog", "Reference", None))
        self.inputType.setItemText(1, _translate("Dialog", "Query", None))
        self.label_11.setText(_translate("Dialog", "Test Type:", None))
        self.testType.setItemText(0, _translate("Dialog", "Projection", None))
        self.testType.setItemText(1, _translate("Dialog", "Jacquard", None))
        self.testType.setItemText(2, _translate("Dialog", "Intersection", None))
        self.label_12.setText(_translate("Dialog", "Group By:", None))
        self.groupBy.setItemText(0, _translate("Dialog", "None", None))
        self.groupBy.setItemText(1, _translate("Dialog", "Regions", None))
        self.groupBy.setItemText(2, _translate("Dialog", "Reads", None))
        self.label_13.setText(_translate("Dialog", "Randomization:", None))
        self.runTests.setText(_translate("Dialog", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tests), _translate("Dialog", "Tests", None))

