# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_emExportDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1171, 691)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.emExport = QtGui.QTableWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.emExport.sizePolicy().hasHeightForWidth())
        self.emExport.setSizePolicy(sizePolicy)
        self.emExport.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.emExport.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.emExport.setObjectName(_fromUtf8("emExport"))
        self.emExport.setColumnCount(0)
        self.emExport.setRowCount(0)
        self.verticalLayout.addWidget(self.emExport)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lpOutputLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lpOutputLineEdit.setObjectName(_fromUtf8("lpOutputLineEdit"))
        self.horizontalLayout_3.addWidget(self.lpOutputLineEdit)
        self.lpOutputButton = QtGui.QToolButton(self.groupBox_3)
        self.lpOutputButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.lpOutputButton.setArrowType(QtCore.Qt.NoArrow)
        self.lpOutputButton.setObjectName(_fromUtf8("lpOutputButton"))
        self.horizontalLayout_3.addWidget(self.lpOutputButton)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lpSharedYComboBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpSharedYComboBox.sizePolicy().hasHeightForWidth())
        self.lpSharedYComboBox.setSizePolicy(sizePolicy)
        self.lpSharedYComboBox.setObjectName(_fromUtf8("lpSharedYComboBox"))
        self.lpSharedYComboBox.addItem(_fromUtf8(""))
        self.lpSharedYComboBox.addItem(_fromUtf8(""))
        self.lpSharedYComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lpSharedYComboBox)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lpColumnComboBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpColumnComboBox.sizePolicy().hasHeightForWidth())
        self.lpColumnComboBox.setSizePolicy(sizePolicy)
        self.lpColumnComboBox.setObjectName(_fromUtf8("lpColumnComboBox"))
        self.lpColumnComboBox.addItem(_fromUtf8(""))
        self.lpColumnComboBox.addItem(_fromUtf8(""))
        self.lpColumnComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lpColumnComboBox)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lpRowComboBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpRowComboBox.sizePolicy().hasHeightForWidth())
        self.lpRowComboBox.setSizePolicy(sizePolicy)
        self.lpRowComboBox.setObjectName(_fromUtf8("lpRowComboBox"))
        self.lpRowComboBox.addItem(_fromUtf8(""))
        self.lpRowComboBox.addItem(_fromUtf8(""))
        self.lpRowComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lpRowComboBox)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lpColorComboBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpColorComboBox.sizePolicy().hasHeightForWidth())
        self.lpColorComboBox.setSizePolicy(sizePolicy)
        self.lpColorComboBox.setObjectName(_fromUtf8("lpColorComboBox"))
        self.lpColorComboBox.addItem(_fromUtf8(""))
        self.lpColorComboBox.addItem(_fromUtf8(""))
        self.lpColorComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lpColorComboBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lpRunButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpRunButton.sizePolicy().hasHeightForWidth())
        self.lpRunButton.setSizePolicy(sizePolicy)
        self.lpRunButton.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lpRunButton.setFont(font)
        self.lpRunButton.setObjectName(_fromUtf8("lpRunButton"))
        self.horizontalLayout_4.addWidget(self.lpRunButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.atOutputLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.atOutputLineEdit.setObjectName(_fromUtf8("atOutputLineEdit"))
        self.horizontalLayout_6.addWidget(self.atOutputLineEdit)
        self.atOutputButton = QtGui.QToolButton(self.groupBox_2)
        self.atOutputButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.atOutputButton.setArrowType(QtCore.Qt.NoArrow)
        self.atOutputButton.setObjectName(_fromUtf8("atOutputButton"))
        self.horizontalLayout_6.addWidget(self.atOutputButton)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.atInputLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.atInputLineEdit.setObjectName(_fromUtf8("atInputLineEdit"))
        self.horizontalLayout_7.addWidget(self.atInputLineEdit)
        self.atInputButton = QtGui.QToolButton(self.groupBox_2)
        self.atInputButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.atInputButton.setArrowType(QtCore.Qt.NoArrow)
        self.atInputButton.setObjectName(_fromUtf8("atInputButton"))
        self.horizontalLayout_7.addWidget(self.atInputButton)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.atInputTypeComboBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atInputTypeComboBox.sizePolicy().hasHeightForWidth())
        self.atInputTypeComboBox.setSizePolicy(sizePolicy)
        self.atInputTypeComboBox.setObjectName(_fromUtf8("atInputTypeComboBox"))
        self.atInputTypeComboBox.addItem(_fromUtf8(""))
        self.atInputTypeComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.atInputTypeComboBox)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.atTestComboBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atTestComboBox.sizePolicy().hasHeightForWidth())
        self.atTestComboBox.setSizePolicy(sizePolicy)
        self.atTestComboBox.setObjectName(_fromUtf8("atTestComboBox"))
        self.atTestComboBox.addItem(_fromUtf8(""))
        self.atTestComboBox.addItem(_fromUtf8(""))
        self.atTestComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.atTestComboBox)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.atGroupByComboBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atGroupByComboBox.sizePolicy().hasHeightForWidth())
        self.atGroupByComboBox.setSizePolicy(sizePolicy)
        self.atGroupByComboBox.setObjectName(_fromUtf8("atGroupByComboBox"))
        self.atGroupByComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.atGroupByComboBox)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_13)
        self.atRandomizationSpinBox = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atRandomizationSpinBox.sizePolicy().hasHeightForWidth())
        self.atRandomizationSpinBox.setSizePolicy(sizePolicy)
        self.atRandomizationSpinBox.setMaximum(999999)
        self.atRandomizationSpinBox.setProperty("value", 500)
        self.atRandomizationSpinBox.setObjectName(_fromUtf8("atRandomizationSpinBox"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.atRandomizationSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.atRunButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atRunButton.sizePolicy().hasHeightForWidth())
        self.atRunButton.setSizePolicy(sizePolicy)
        self.atRunButton.setMinimumSize(QtCore.QSize(200, 40))
        self.atRunButton.setObjectName(_fromUtf8("atRunButton"))
        self.horizontalLayout_5.addWidget(self.atRunButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.exportButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout_8.addWidget(self.exportButton)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_8.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Experimental Matrix Export", None))
        self.label.setText(_translate("Dialog", "Experimental Matrix", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Regions-to-Reads Tests", None))
        self.label_4.setText(_translate("Dialog", "Output Folder:", None))
        self.lpOutputButton.setText(_translate("Dialog", "...", None))
        self.label_5.setText(_translate("Dialog", "Shared y-axis:", None))
        self.lpSharedYComboBox.setItemText(0, _translate("Dialog", "None", None))
        self.lpSharedYComboBox.setItemText(1, _translate("Dialog", "Rows", None))
        self.lpSharedYComboBox.setItemText(2, _translate("Dialog", "Columns", None))
        self.label_6.setText(_translate("Dialog", "Column:", None))
        self.lpColumnComboBox.setItemText(0, _translate("Dialog", "None", None))
        self.lpColumnComboBox.setItemText(1, _translate("Dialog", "Reads", None))
        self.lpColumnComboBox.setItemText(2, _translate("Dialog", "Regions", None))
        self.label_7.setText(_translate("Dialog", "Row:", None))
        self.lpRowComboBox.setItemText(0, _translate("Dialog", "None", None))
        self.lpRowComboBox.setItemText(1, _translate("Dialog", "Reads", None))
        self.lpRowComboBox.setItemText(2, _translate("Dialog", "Regions", None))
        self.label_8.setText(_translate("Dialog", "Color:", None))
        self.lpColorComboBox.setItemText(0, _translate("Dialog", "None", None))
        self.lpColorComboBox.setItemText(1, _translate("Dialog", "Reads", None))
        self.lpColorComboBox.setItemText(2, _translate("Dialog", "Regions", None))
        self.lpRunButton.setText(_translate("Dialog", "Run Lineplot", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Regions-to-Regions Tests", None))
        self.label_10.setText(_translate("Dialog", "Output Folder:", None))
        self.atOutputButton.setText(_translate("Dialog", "...", None))
        self.label_15.setText(_translate("Dialog", "Input Matrix:", None))
        self.atInputButton.setText(_translate("Dialog", "...", None))
        self.label_16.setText(_translate("Dialog", "Input Type:", None))
        self.atInputTypeComboBox.setItemText(0, _translate("Dialog", "Reference", None))
        self.atInputTypeComboBox.setItemText(1, _translate("Dialog", "Query", None))
        self.label_11.setText(_translate("Dialog", "Test Type:", None))
        self.atTestComboBox.setItemText(0, _translate("Dialog", "Projection", None))
        self.atTestComboBox.setItemText(1, _translate("Dialog", "Jaccard", None))
        self.atTestComboBox.setItemText(2, _translate("Dialog", "Intersection", None))
        self.label_12.setText(_translate("Dialog", "Group By:", None))
        self.atGroupByComboBox.setItemText(0, _translate("Dialog", "None", None))
        self.label_13.setText(_translate("Dialog", "Randomization:", None))
        self.atRunButton.setText(_translate("Dialog", "Run Association Test", None))
        self.exportButton.setText(_translate("Dialog", "Save Matrix as...", None))

